// bgStats.ts — build a Board Game Stats play file from the player's saved games.
//
// This used to be generated by the data service (`GET /me/games/bgstats`). It moved here
// for two reasons, both of which the server could not do without an API change:
//
//   * **Only the plays the player picked.** The history screen has checkboxes now; the
//     server endpoint exports everything or nothing.
//   * **The mode.** The server wrote `board: "Solo - Chronobot"` on every play, including
//     Chronossus ones, and named the opponent "Chronobot" — so a Doomsday game imported as
//     a Chronobot game. It has no way to know better: the mode lives in the row's
//     `difficulty` label and `payload`, which this app writes and this app understands.
//
// The output shape is copied from what the service emitted, so existing imports keep
// working — same `about` string, same `games`/`players`/`plays` keys, scores as strings.
import type { GameRow } from './gameData';

/** BG Stats' id for Anachrony, as the service used. */
const BGG_ID = 185343;

export interface BgStatsFile {
  about: string;
  games: { bggId: number; name: string; id: number }[];
  locations: unknown[];
  players: { id: number; name: string; isAnonymous?: boolean }[];
  plays: {
    gameRefId: number;
    /** BG Stats' per-play "board"/mode field — the opponent and its modules. */
    board: string;
    /** Free text. Difficulty options only; the mode is in `board`, not repeated here. */
    comments: string;
    playDate: string;
    rounds?: number;
    playerScores: { playerRefId: number; score: string; winner: boolean }[];
  }[];
}

/**
 * What a saved row says about the game it came from.
 *
 * Rows are written as `"<Bot> · <modules> · <options>"` with `payload.opponent` and
 * `payload.modes` alongside. Older rows predate that: some are just `"Chronossus"`, some
 * are a bare option list from the Chronobot, and imported rows can be anything at all. So
 * the payload is preferred, the label is the fallback, and neither is required.
 */
export function describeGame(row: GameRow): {
  opponent: string | null;
  modes: string[];
  difficulty: string;
} {
  const payload = (row.payload ?? {}) as { opponent?: string; modes?: string[] };
  const parts = (row.difficulty ?? '').split('·').map((s) => s.trim()).filter(Boolean);

  const labelled = parts[0] === 'Chronobot' || parts[0] === 'Chronossus' ? parts[0] : null;
  const opponent = payload.opponent ?? labelled;

  // With a labelled row the segments are [bot, modules, options]; without one, the whole
  // label is the difficulty (that is what the old Chronobot rows look like).
  const modes = payload.modes?.length
    ? payload.modes
    : labelled && parts[1]
      ? parts[1].split('+').map((s) => s.trim()).filter(Boolean)
      : [];
  const difficulty = labelled ? parts.slice(2).join(' · ') : parts.join(' · ');

  return { opponent, modes, difficulty };
}

/**
 * The play's `board` — BG Stats' mode field. The opponent, plus its modules when they are
 * more than the plain base game, so BG Stats accumulates one entry per real mode rather
 * than lumping every play under a single board.
 */
export function boardLabel(row: GameRow): string {
  const { opponent, modes } = describeGame(row);
  const named = modes.filter((m) => m && m !== 'Base');
  const bot = opponent ?? 'Solo';
  return named.length ? `Solo - ${bot} - ${named.join(' + ')}` : `Solo - ${bot}`;
}

/** BG Stats wants `YYYY-MM-DD HH:MM:SS`; rows carry a plain date. */
function playDate(row: GameRow): string {
  const d = (row.played_at ?? '').slice(0, 10);
  return d ? `${d} 00:00:00` : '';
}

/**
 * Build the file. `rows` is already the selection — the caller decides whether that is
 * every game or only the ticked ones.
 *
 * One `players` entry per distinct opponent that actually appears, so a history holding
 * both bots names both rather than calling everything "Chronobot".
 */
export function buildBgStatsExport(rows: GameRow[], playerName: string): BgStatsFile {
  const opponents = [...new Set(rows.map((r) => describeGame(r).opponent ?? 'Solo opponent'))];
  const playerId = 1;
  const opponentId = new Map(opponents.map((name, i) => [name, i + 2]));

  return {
    about: 'This is a Play file that can be read by Board Game Stats.',
    games: [{ bggId: BGG_ID, name: 'Anachrony', id: 1 }],
    locations: [],
    players: [
      { id: playerId, name: playerName },
      ...opponents.map((name) => ({ id: opponentId.get(name)!, name, isAnonymous: true })),
    ],
    plays: rows.map((r) => {
      const { opponent, difficulty } = describeGame(r);
      const botId = opponentId.get(opponent ?? 'Solo opponent')!;
      return {
        gameRefId: 1,
        board: boardLabel(r),
        comments: difficulty,
        playDate: playDate(r),
        ...(r.era_reached != null ? { rounds: r.era_reached } : {}),
        playerScores: [
          {
            playerRefId: playerId,
            score: String(r.player_score ?? ''),
            winner: !!r.won,
          },
          { playerRefId: botId, score: String(r.bot_score), winner: !r.won },
        ],
      };
    }),
  };
}

/** Filename for the download, dated so repeated exports don't overwrite each other. */
export function bgStatsFilename(today: string): string {
  return `anachrony-bgstats-${today}.json`;
}
